utilities (#20)

diff --git a/.github/workflows/clovis.yml b/.github/workflows/clovis.yml
--- a/.github/workflows/clovis.yml
+++ b/.github/workflows/clovis.yml
@@ -69,35 +69,32 @@ jobs:
     - name: Test
       run: ctest --test-dir build --build-config ${{ env.BUILD_TYPE }} --output-on-failure
 
-    - name: Bench
-      if: env.COMPILER != 'gcc' || env.OPERATING_SYSTEM != 'windows'
-      shell: bash
-      working-directory: ./build
-      run: |
-        ./bin/$BUILD_TYPE/clovis bench > output
-        
-        expected=14914348
-        actual=$(grep -o 'bench:[[:space:]]*[0-9][0-9]*' output | grep -o '[0-9][0-9]*')
-        echo "Actual ${actual} Expected ${expected}"
-
-        if [[ "$expected" != "$actual" ]]; then
-          echo "Values did not match."
-          exit 1
-        fi
-
     - name: Perft
-      if: env.BUILD_TYPE == 'Release' && (env.COMPILER != 'gcc' || env.OPERATING_SYSTEM != 'windows')
+      if: env.BUILD_TYPE == 'Release'
       shell: bash
       run: | 
         set -e # Exit immediately if a command exits with a non-zero status
-        ./build/bin/$BUILD_TYPE/clovis perft
+        ./build/bin/$BUILD_TYPE/clovis perft ./resources/perft.epd > /dev/null
 
-    - name: Archive Output
-      if: always()
-      uses: actions/upload-artifact@v2
-      with:
-        name: bench-output
-        path: output
+    - name: Benchmark
+      shell: bash
+      run: python tools/bench.py build/bin/$BUILD_TYPE/clovis 14299399 resources/bench.csv
+
+    - name: Process Data
+      if: env.BUILD_TYPE == 'Release'
+      shell: bash
+      run: | 
+        set -e # Exit immediately if a command exits with a non-zero status
+        ./build/bin/$BUILD_TYPE/process resources/games.pgn resources/processed.epd 100000 > /dev/null
+      #run: python tools/process.py build/bin/$BUILD_TYPE/clovis resources/games.pgn resources/processed.epd
+
+    - name: Tune Evaluation
+      if: env.BUILD_TYPE == 'Release'
+      shell: bash
+      run: | 
+        set -e # Exit immediately if a command exits with a non-zero status
+        cat resources/processed.epd >> resources/quiet-labeled.epd
+        ./build/bin/$BUILD_TYPE/clovis tune ./resources/quiet-labeled.epd 300
 
   # =========================================================
   # Self Play Job
@@ -109,6 +106,11 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
 
+    - name: Install Clang
+      uses: KyleMayes/install-llvm-action@v1
+      with:
+        version: "17.0"
+
     - name: Install Conan
       id: conan
       uses: turtlebrowser/get-conan@main
@@ -117,10 +119,10 @@ jobs:
       uses: lukka/get-cmake@latest
 
     - name: Configure
-      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
+      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTS=OFF -DBUILD_TOOLS=OFF
 
     - name: Build
-      run: cmake --build build --parallel --config debug
+      run: cmake --build build --parallel --config Release
 
     - name: Checkout cutechess
       uses: actions/checkout@v4
@@ -161,9 +163,7 @@ jobs:
           -sprt elo0=0 elo1=10 alpha=0.05 beta=0.05 \
           -concurrency 32 \
           -resultformat "results - %s wins, %s draws, %s losses" > results.log
-        
-        cat results.log
-      
+              
         los_line=$(grep "LOS:" results.log)
         echo "LOS line: $los_line"
         
@@ -262,7 +262,7 @@ jobs:
         sudo apt-get install -y gcovr
 
     - name: Configure
-      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -G Ninja -DCOVERAGE=ON
+      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -G Ninja -DCOVERAGE=ON -DBUILD_TOOLS=OFF
 
     - name: Build
       run: cmake --build build --parallel --config debug
