Update clovis.yml

diff --git a/.github/workflows/clovis.yml b/.github/workflows/clovis.yml
--- a/.github/workflows/clovis.yml
+++ b/.github/workflows/clovis.yml
@@ -118,6 +118,25 @@ jobs:
       run: find src \( -name '*.cpp' -o -name '*.h' \) -exec clang-format -Werror --style=file -n {} +
 
   # =========================================================
+  # Editor Config Job
+  # =========================================================
+  editorconfig:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+    
+    - name: Install editorconfig-checker
+      uses: editorconfig-checker/action-editorconfig-checker@main
+
+    - name: Check CMakeLists.txt formatting
+      run: find . \( -name 'CMakeLists.txt' \) -exec editorconfig-checker {} \+ || { echo "EditorConfig check failed! See the README if you don't know how to fix this."; exit 1; }
+
+    - name: Check C++ formatting
+      run: find src examples \( -name '*.cpp' -o -name '*.hpp' \) -exec editorconfig-checker {} \+ || { echo "EditorConfig check failed! See the README if you don't know how to fix this."; exit 1; }
+
+  # =========================================================
   # Clang Tidy Job
   # =========================================================
   clang-tidy:
