Update clovis.yml

diff --git a/.github/workflows/clovis.yml b/.github/workflows/clovis.yml
--- a/.github/workflows/clovis.yml
+++ b/.github/workflows/clovis.yml
@@ -103,7 +103,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Clovis code
+    - name: Checkout code
       uses: actions/checkout@v4
 
     - name: Install Clang
@@ -111,57 +111,69 @@ jobs:
       with:
         version: "17.0"
 
+    - name: Install Conan
+      id: conan
+      uses: turtlebrowser/get-conan@main
+
     - name: Install CMake
       uses: lukka/get-cmake@latest
 
-    - name: Configure Clovis
+    - name: Configure
       run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTS=OFF -DBUILD_TOOLS=OFF
 
-    - name: Build Clovis
+    - name: Build
       run: cmake --build build --parallel --config Release
 
-    - name: Checkout fast-chess repo
+    - name: Checkout cutechess
       uses: actions/checkout@v4
       with:
-        repository: Disservin/fast-chess
-        path: fast-chess
+        repository: cutechess/cutechess
+        path: cutechess
         ref: master
+        persist-credentials: false
 
-    - name: Build fast-chess
-      working-directory: fast-chess
-      run: make -j
-
+    - name: Install dependencies
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y qtbase5-dev qt5-qmake libqt5svg5-dev
+    
+    - name: Build cutechess
+      working-directory: cutechess
+      run: |
+        mkdir build
+        cd build
+        cmake ..
+        make -j
+    
     - name: Download clovis-release-gcc-linux artifact
       run: |
         curl -L -o build/clovis-release-gcc-linux https://github.com/jonathanmcdermid/Clovis/releases/download/III/clovis-release-gcc-linux
         chmod +x build/clovis-release-gcc-linux
-
-    - name: Run self-play games
+    
+    - name: Self-play
+      shell: bash
+      working-directory: cutechess
       run: |
         set -e
-        ./fast-chess/fast-chess \
-          -engine cmd=build/bin/Release/clovis name=clovis-new \
-          -engine cmd=build/clovis-release-gcc-linux name=clovis-old \
-          -each tc=5+0.1 \
-          -openings file=fast-chess/app/tests/data/openings.epd format=epd order=random \
-          -rounds 200 \
-          -repeat \
-          -concurrency 4 \
-          -pgnout file=self-play.pgn \
-          -maxmoves 200 \
+        ./build/cutechess-cli \
+          -engine name=clovis-old cmd="../build/clovis-release-gcc-linux" \
+          -engine name=clovis-new cmd="../build/bin/Release/clovis" \
+          -each proto=uci tc=inf/5+0.1 \
+          -games 2 -rounds 200 -repeat 2 -maxmoves 200 \
           -sprt elo0=0 elo1=10 alpha=0.05 beta=0.05 \
-
-    - name: Upload PGN file
-      uses: actions/upload-artifact@v4.3.0
-      with:
-        name: self-play-pgn
-        path: self-play.pgn
-
-    - name: Upload Log file
-      uses: actions/upload-artifact@v4.3.0
-      with:
-        name: log.txt
-        path: log.txt
+          -concurrency 32 \
+          -resultformat "results - %s wins, %s draws, %s losses" > results.log
+              
+        los_line=$(grep "LOS:" results.log)
+        echo "LOS line: $los_line"
+        
+        los_percentage=$(echo "$los_line" | awk '{print $7}' | tr -d '%')
+        echo "LOS percentage: $los_percentage"
+        
+        if [ $(echo "$los_percentage < 5.0" | bc) -eq 1 ]; then
+          echo "Error: Likelihood of superiority (LOS) is less than 10%."
+          exit 1
+        fi
 
   # =========================================================
   # Clang Format Job
